const puppeteer = require('puppeteer');
const ViewerGeneratorService = require('./viewer-generator.service');

class PdfGeneratorService {
  static async generatePdf(markdown, repoName, stats = {}) {
    const html = ViewerGeneratorService.generateViewerHtml(markdown, repoName, stats);

    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
    });

    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0', timeout: 30000 });

      await page.evaluate(() => {
        return new Promise(resolve => {
          if (typeof mermaid === 'undefined') { resolve(); return; }
          const check = setInterval(() => {
            const pending = document.querySelectorAll('.mermaid:not([data-processed])');
            if (pending.length === 0) { clearInterval(check); resolve(); }
          }, 200);
          setTimeout(() => { clearInterval(check); resolve(); }, 8000);
        });
      });

      const pdf = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
        displayHeaderFooter: true,
        headerTemplate: '<span></span>',
        footerTemplate: `<div style="font-size:10px;color:#64748b;text-align:center;width:100%;padding:0 20mm;">
          Generated by Auto-Doc — ${repoName} — Page <span class="pageNumber"></span> of <span class="totalPages"></span>
        </div>`
      });

      return Buffer.from(pdf);
    } finally {
      await browser.close();
    }
  }
}

module.exports = PdfGeneratorService;
