/**
 * scripts/generate-docs-ci.js
 *
 * Runs the Auto-Doc pipeline in CI mode.
 * Aligned with AuditLog (PascalCase), Repository (FetchFiles),
 * and Documentation (#content getter) models.
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');

// ── OOP imports ──────────────────────────────────────────────────
const Repository = require('../src/models/repository.model');
const sanitizerService = require('../src/services/sanitizer.service');

// ── Config ────────────────────────────────────────────────────────
const REPO_URL = process.env.REPO_URL;
const DOC_MODE = (process.env.DOC_MODE || 'agentic').toLowerCase();
const PROVIDER = (process.env.DOC_PROVIDER || 'groq').toLowerCase();
const OUTPUT_DIR = path.join(__dirname, '../docs');

if (!REPO_URL) {
  console.error('❌ REPO_URL environment variable is required');
  process.exit(1);
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function writeDoc(filename, content) {
  const filepath = path.join(OUTPUT_DIR, filename);
  fs.writeFileSync(filepath, content, 'utf-8');
  console.log(`    Written: docs/${filename} (${content.length} chars)`);
}

function timestamp() {
  return new Date().toISOString().replace('T', ' ').substring(0, 19);
}

// ── Main Pipeline ─────────────────────────────────────────────────
async function run() {
  console.log('\n🚀 Auto-Doc CI Pipeline starting...');
  console.log(`   Repository: ${REPO_URL}`);
  console.log(`   Mode:       ${DOC_MODE}`);

  ensureDir(OUTPUT_DIR);

  // ── Step 1: Fetch repository files ─────────────────────────────
  const repository = new Repository(REPO_URL);
  await repository.FetchFiles(); // Octokit-based fetching

  const files = repository.files;
  if (!files || files.length === 0) {
    console.error('❌ No files fetched — check REPO_URL and GITHUB_TOKEN');
    process.exit(1);
  }

  // ── Step 2: Security audit ─────────────────────────────────────
  console.log('🔒 Step 2: Running security audit...');
  const auditLog = repository.auditLog; 
  
  // Clear sanitizer vault for a fresh CI run
  if (sanitizerService.resetVault) {
    sanitizerService.resetVault();
  } else if (sanitizerService.vault) {
    sanitizerService.vault.clear();
  }

  for (const file of files) {
    // Aligned with AuditLog.js: IncrementScanned (PascalCase)
    auditLog.IncrementScanned(); 
    
    const content = file.content || '';
    const findings = sanitizerService.audit(content);
    
    if (findings.length > 0) {
      // Aligned with AuditLog.js: RecordEntry (PascalCase)
      // Pass the file object so RecordEntry can access file.path
      auditLog.RecordEntry(file, findings);
    }
  }

  // Aligned with AuditLog.js: GetSummary (PascalCase)
  const auditSummary = auditLog.GetSummary();

  if (auditSummary.totalRedacted > 0) {
    console.warn(`   ⚠️  ${auditSummary.totalRedacted} secrets detected across ${auditSummary.filesAffected} files.`);
  } else {
    console.log('   ✅ No secrets detected.');
  }

  // ── Step 3: Generate documentation ─────────────────────────────
  console.log(`📝 Step 3: Generating documentation (${DOC_MODE})...`);
  
  // repository.GenerateDocumentation internally handles:
  // 1. Sanitization 2. Chunking/Orchestration 3. Reintegration
  const docs = await repository.GenerateDocumentation(DOC_MODE, PROVIDER);

  // Aligned with Documentation.js: get content() getter
  const documentation = docs.content || '';
  const stats = docs.stats || {};

  // ── Step 4: Write output files ─────────────────────────────────
  console.log('\n📄 Step 4: Writing documentation files...');

  writeDoc('README.md', buildReadme(repository.name, documentation, REPO_URL));
  writeDoc('index.html', buildHTMLPage(repository.name, documentation));
  writeDoc('SECURITY.md', buildSecurityReport(auditSummary, repository.name));

  writeDoc('pipeline-meta.json', JSON.stringify({
    generatedAt: new Date().toISOString(),
    repository: REPO_URL,
    repoName: repository.name,
    mode: DOC_MODE,
    provider: PROVIDER,
    filesAnalyzed: auditSummary.filesScanned,
    totalRedacted: auditSummary.totalRedacted,
    stats
  }, null, 2));

  console.log('\n🎉 Pipeline complete!');
}

// ── Document Builders ─────────────────────────────────────────────

function buildReadme(repoName, documentation, repoUrl) {
  return `# 📚 Documentation: ${repoName}

> Auto-generated by Auto-Doc on ${timestamp()}
> [View Live Site](https://${repoUrl.split('github.com/')[1].split('/')[0]}.github.io/${repoName}/)

---

${documentation}

---
*Powered by Auto-Doc*`;
}

function buildHTMLPage(repoName, documentation) {
  // Enhanced MD to HTML conversion
  const htmlBody = documentation
    .replace(/^### (.*$)/gim, '<h3 class="text-xl font-bold mt-6 mb-2">$1</h3>')
    .replace(/^## (.*$)/gim, '<h2 class="text-2xl font-bold mt-8 mb-4 border-b pb-2">$1</h2>')
    .replace(/^# (.*$)/gim, '<h1 class="text-4xl font-extrabold mb-6">$1</h1>')
    .replace(/^\- (.*$)/gim, '<li class="ml-4 list-disc">$1</li>')
    .replace(/\*\*(.*)\*\*/gim, '<strong>$1</strong>')
    .replace(/`(.*?)`/gim, '<code class="bg-gray-200 px-1 rounded">$1</code>')
    .replace(/\n/gim, '<br>');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${repoName} Docs</title>
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-50 text-gray-900 leading-relaxed">
  <nav class="bg-white border-b px-10 py-4 flex justify-between items-center sticky top-0">
    <h1 class="font-bold text-lg text-emerald-600">Auto-Doc ⚡</h1>
    <span class="text-xs text-gray-400 font-mono">${timestamp()}</span>
  </nav>
  <main class="max-w-4xl mx-auto my-12 bg-white p-12 rounded-3xl shadow-xl border border-gray-100">
    <div class="prose max-w-none">
      ${htmlBody}
    </div>
  </main>
  <footer class="text-center pb-12 text-gray-400 text-sm">
    &copy; ${new Date().getFullYear()} Generated securely by Auto-Doc CI Pipeline
  </footer>
</body>
</html>`;
}

function buildSecurityReport(summary, repoName) {
  const { filesScanned, filesAffected, totalRedacted, findings } = summary;

  // Uses 'findings' and 'f.file' from AuditLog.js GetSummary()
  const findingsList = findings && findings.length > 0
    ? findings.map(f => `### \`${f.file}\`\n- Redacted patterns: ${f.patterns.join(', ')}`).join('\n')
    : '_No sensitive data detected._';

  return `# 🔒 Security Audit Report: ${repoName}

## Summary
| Metric | Value |
|---|---|
| Files Scanned | ${filesScanned} |
| Files with Secrets | ${filesAffected} |
| Total Redactions | ${totalRedacted} |

## Findings
${findingsList}

---
*This report confirms that all secrets were anonymized locally before LLM processing.*`;
}

run().catch(err => {
  console.error('\n❌ Pipeline failed:', err.message);
  process.exit(1);
});